{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "24d8277c-a286-41ab-8e31-f477c874e89c",
   "metadata": {},
   "outputs": [],
   "source": [
    "risk_app/\n",
    "├─ app.py                  # Streamlit 앱 메인 코드\n",
    "├─ train_2019_2024.csv     # 파생변수까지 포함된 train 데이터\n",
    "├─ test_2025.csv            # 2025 데이터 (파생변수 포함)\n",
    "├─ requirements.txt        # 필요한 라이브러리\n",
    "\n",
    "pandas\n",
    "streamlit\n",
    "scikit-learn\n",
    "openpyxl\n",
    "\n",
    "import pandas as pd\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "import streamlit as st\n",
    "\n",
    "# -------------------------------\n",
    "# 1️⃣ 데이터 불러오기\n",
    "# -------------------------------\n",
    "train_df = pd.read_excel(\"train_2019_2024.xlsx\")\n",
    "test_df  = pd.read_excel(\"test_2025.xlsx\")\n",
    "\n",
    "# -------------------------------\n",
    "# 2️⃣ 위험지수 계산에 필요한 컬럼\n",
    "# -------------------------------\n",
    "to_scale = ['closure_rate', 'sales_per_store_inv', 'traffic_conversion_rate', 'store_density', 'franchise_ratio_change']\n",
    "\n",
    "# -------------------------------\n",
    "# 3️⃣ Min-Max 스케일링 (train 기준)\n",
    "# -------------------------------\n",
    "scaler = MinMaxScaler()\n",
    "scaler.fit(train_df[to_scale])\n",
    "\n",
    "train_scaled = pd.DataFrame(scaler.transform(train_df[to_scale]), columns=to_scale, index=train_df.index)\n",
    "test_scaled  = pd.DataFrame(scaler.transform(test_df[to_scale]), columns=to_scale, index=test_df.index)\n",
    "\n",
    "# -------------------------------\n",
    "# 4️⃣ 가중치 정의 및 risk_score 계산\n",
    "# -------------------------------\n",
    "weights = {\n",
    "    'closure_rate': 0.30,\n",
    "    'sales_per_store_inv': 0.25,\n",
    "    'traffic_conversion_rate': 0.20,\n",
    "    'store_density': 0.15,\n",
    "    'franchise_ratio_change': 0.10\n",
    "}\n",
    "\n",
    "train_df['risk_score'] = 0\n",
    "test_df['risk_score'] = 0\n",
    "for col, w in weights.items():\n",
    "    train_df['risk_score'] += train_scaled[col] * w\n",
    "    test_df['risk_score']  += test_scaled[col] * w\n",
    "\n",
    "# -------------------------------\n",
    "# 5️⃣ 사분위수 기준 risk_level 부여 (train 기준)\n",
    "# -------------------------------\n",
    "q1 = train_df['risk_score'].quantile(0.25)\n",
    "q2 = train_df['risk_score'].quantile(0.50)\n",
    "q3 = train_df['risk_score'].quantile(0.75)\n",
    "\n",
    "def risk_level(score):\n",
    "    if score < q1:\n",
    "        return 'Low Risk'\n",
    "    elif score < q2:\n",
    "        return 'Medium Risk'\n",
    "    elif score < q3:\n",
    "        return 'High Risk'\n",
    "    else:\n",
    "        return 'Critical Risk'\n",
    "\n",
    "test_df['risk_level'] = test_df['risk_score'].apply(risk_level)\n",
    "\n",
    "# -------------------------------\n",
    "# 6️⃣ Streamlit 앱 UI\n",
    "# -------------------------------\n",
    "st.title(\"2025 상권 위험지수 분석\")\n",
    "\n",
    "# 6-1. 전체 요약\n",
    "st.subheader(\"전체 위험지수 요약\")\n",
    "risk_summary = test_df['risk_level'].value_counts()\n",
    "st.bar_chart(risk_summary)\n",
    "\n",
    "# 6-2. 구/상권별 팝업형 선택\n",
    "st.subheader(\"구/상권별 위험지수 확인\")\n",
    "district_list = test_df['district'].unique()\n",
    "selected_district = st.selectbox(\"구 선택\", district_list)\n",
    "\n",
    "sub_df = test_df[test_df['district'] == selected_district]\n",
    "market_list = sub_df['market'].unique()\n",
    "selected_market = st.selectbox(\"상권 선택\", market_list)\n",
    "\n",
    "market_row = sub_df[sub_df['market'] == selected_market].iloc[0]\n",
    "\n",
    "st.info(\n",
    "    f\"구: {market_row['district']}\\n\"\n",
    "    f\"상권: {market_row['market']}\\n\"\n",
    "    f\"Risk Score: {market_row['risk_score']:.3f}\\n\"\n",
    "    f\"Risk Level: {market_row['risk_level']}\"\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
